pipeline {
    agent { 
	    label 'dslave' 
	} 
    stages {
        stage('Build') {
            steps {
                sh 'java -version'
				echo "Get working directory"
				sh 'pwd'
            }
        }
    }
}
